"""add_new_fields_to_asset_and_user

Revision ID: 2633bd141019
Revises: 0002
Create Date: 2026-01-08 17:24:20.230195

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2633bd141019"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assets", sa.Column("count", sa.Integer(), nullable=False, server_default="1")
    )
    op.add_column("assets", sa.Column("model", sa.String(), nullable=True))
    op.add_column("assets", sa.Column("serial_number", sa.String(), nullable=True))
    op.add_column(
        "assets",
        sa.Column(
            "check_in_date",
            sa.Date(),
            nullable=False,
            server_default=sa.func.current_date(),
        ),
    )
    op.add_column("assets", sa.Column("check_out_date", sa.Date(), nullable=True))
    op.alter_column("assets", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("assets", "type", existing_type=sa.VARCHAR(), nullable=False)
    op.add_column("users", sa.Column("name", sa.String(), nullable=True))
    op.add_column("users", sa.Column("phone", sa.String(), nullable=True))
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_constraint(op.f("users_email_key"), "users", type_="unique")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_unique_constraint(
        op.f("users_email_key"), "users", ["email"], postgresql_nulls_not_distinct=False
    )
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("users", "phone")
    op.drop_column("users", "name")
    op.alter_column("assets", "type", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("assets", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("assets", "check_out_date")
    op.drop_column("assets", "check_in_date")
    op.drop_column("assets", "serial_number")
    op.drop_column("assets", "model")
    op.drop_column("assets", "count")
    # ### end Alembic commands ###
